// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Auditactweb
{
    public int Idauditact { get; set; }

    public int Ideftocnt { get; set; }

    public string Codusrcre { get; set; }

    public DateTime Fchappcre { get; set; }

    public int? Idcanal { get; set; }

    public string Codref { get; set; }

    public DateTime Fchcre { get; set; }

    public string Creips { get; set; }

    public string Crehsn { get; set; }

    public string Appname { get; set; }
}