// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Audusop
{
    public int Idaudusop { get; set; }

    public string Idsesapp { get; set; }

    public int Ideobj { get; set; }

    public int Ideusr { get; set; }

    public string Codusr { get; set; }

    public DateTime? Fchappcre { get; set; }

    public DateTime? Fchcre { get; set; }

    public string Creips { get; set; }

    public string Crehsn { get; set; }

    public string Appname { get; set; }
}