// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Catalogo de Motivos de Anulacion de facturas
/// </summary>
public partial class CatmotivosAnulacion
{
    public int IdmotivoAnulacion { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }
}