// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Catservicioperfil
{
    public int Id { get; set; }

    public int Idintegracion { get; set; }

    public int Idservicio { get; set; }

    public int Idreferencia { get; set; }

    public string DescripcionReferencia { get; set; }

    public int Idperfil { get; set; }

    public string DescripcionPerfil { get; set; }
}