// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ModeloPrincipal.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ModeloPrincipal.Entity
{
    public partial class CVGEntities
    {
        private ICVGEntitiesProcedures _procedures;

        public virtual ICVGEntitiesProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CVGEntitiesProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICVGEntitiesProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CVGEntitiesProcedures : ICVGEntitiesProcedures
    {
        private readonly CVGEntities _context;

        public CVGEntitiesProcedures(CVGEntities context)
        {
            _context = context;
        }

        public virtual async Task<List<spObtenerContratosDisponiblesResult>> spObtenerContratosDisponiblesAsync(int? iDEUSUARIO, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDEUSUARIO",
                    Value = iDEUSUARIO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spObtenerContratosDisponiblesResult>("EXEC @returnValue = [CLI].[spObtenerContratosDisponibles] @IDEUSUARIO = @IDEUSUARIO", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spObtenerFacturasColectorResult>> spObtenerFacturasColectorAsync(int? idUsuario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IdUsuario",
                    Value = idUsuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spObtenerFacturasColectorResult>("EXEC @returnValue = [CXC].[spObtenerFacturasColector] @IdUsuario = @IdUsuario", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
