// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Datainverseguro
{
    public int IdCnt { get; set; }

    public string Cedula { get; set; }

    public string Sexo { get; set; }

    public DateOnly FchIni { get; set; }

    public DateOnly? FchFin { get; set; }

    public string Sucursal { get; set; }

    public string Nodo { get; set; }

    public string Barrio { get; set; }

    public int? Edad { get; set; }

    public DateOnly? FchAnu { get; set; }

    public decimal MtoCor { get; set; }

    public decimal MtoDol { get; set; }

    public byte? DiaPag { get; set; }

    public string Tecn { get; set; }

    public int? CantMeses { get; set; }

    public decimal Mbps { get; set; }

    public string EstadoTv { get; set; }

    public string EstadoInternet { get; set; }

    public string FormaPago { get; set; }
}