// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Detalle de contrato
/// </summary>
public partial class Detcnt
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idedetcnt { get; set; }

    /// <summary>
    /// Identity de las CIAS o Compañias
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Id del Contrato 
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Tipo de contrato bajo cual suscribe el servicio (0=Contrato Original, 1= Ademdun)
    /// </summary>
    public byte Tipcnt { get; set; }

    /// <summary>
    /// Id de la clase de servicio.
    /// </summary>
    public int Ideclssrvprd { get; set; }

    /// <summary>
    /// Id del servicio Contratado
    /// </summary>
    public int Idesrvprd { get; set; }

    /// <summary>
    /// Id del Agente
    /// </summary>
    public int Ideagente { get; set; }

    public int Idemon { get; set; }

    /// <summary>
    /// Fecha Inicial del Servicio
    /// </summary>
    public DateOnly Fchini { get; set; }

    /// <summary>
    /// Fecha Final del Servicio
    /// </summary>
    public DateOnly Fchfin { get; set; }

    public DateOnly? Fchins { get; set; }

    /// <summary>
    /// Estado Técnico == 1=Activo(Instalado), 2=Cortado, 4=Anulacion del Contrato, 8=Anulacion de la Venta, 16 = Registrado, 32 = Suspendido.
    /// </summary>
    public byte Esttec { get; set; }

    /// <summary>
    /// Id Plan de Venta bajo el cual contrata el servicio.
    /// </summary>
    public int? Ideplavta { get; set; }

    /// <summary>
    /// Identity del Detalle del Plan de Venta
    /// </summary>
    public int? Idedetplavta { get; set; }

    /// <summary>
    /// Id del Maestro de Lista de Precio
    /// </summary>
    public int Idelstpre { get; set; }

    /// <summary>
    /// Id sucursal
    /// </summary>
    public int Idesuc { get; set; }

    /// <summary>
    /// Id del departamento
    /// </summary>
    public int Idedep { get; set; }

    /// <summary>
    /// Id del Municipio
    /// </summary>
    public int Idemun { get; set; }

    /// <summary>
    /// Id de la Zona
    /// </summary>
    public int Idezon { get; set; }

    /// <summary>
    /// Id de la subzona
    /// </summary>
    public int Ideszn { get; set; }

    /// <summary>
    /// Direccion de instalacion del servicio
    /// </summary>
    public string Dirsrv { get; set; }

    /// <summary>
    /// Iva del Producto o Servicio
    /// </summary>
    public decimal Ivapre { get; set; }

    /// <summary>
    /// Subtotal de Precio del Servicio o Producto Local
    /// </summary>
    public decimal Subpreloc { get; set; }

    /// <summary>
    /// Monto del Descuento Local
    /// </summary>
    public decimal Mtodesloc { get; set; }

    /// <summary>
    /// Monto de IVA Local
    /// </summary>
    public decimal Mtoivaloc { get; set; }

    /// <summary>
    /// Total del Precio del Producto o Servicio Local
    /// </summary>
    public decimal Totpreloc { get; set; }

    /// <summary>
    /// Subtotal de Precio del Servicio o Producto Foraneo
    /// </summary>
    public decimal Subprefor { get; set; }

    /// <summary>
    /// Monto de Descuento Foraneo
    /// </summary>
    public decimal Mtodesfor { get; set; }

    /// <summary>
    /// Monto de IVA Foraneo
    /// </summary>
    public decimal Mtoivafor { get; set; }

    /// <summary>
    /// Total del Precio del Producto o Servicio Foraneo
    /// </summary>
    public decimal Totprefor { get; set; }

    /// <summary>
    /// Subtotal de Precio del Servicio o Producto Extra
    /// </summary>
    public decimal Subprextr { get; set; }

    /// <summary>
    /// Monto de Descuento Extra
    /// </summary>
    public decimal Mtodesxtr { get; set; }

    /// <summary>
    /// Monto de IVA Extra
    /// </summary>
    public decimal Mtoivaxtr { get; set; }

    /// <summary>
    /// Total del Precio del Producto o Servicio Extra
    /// </summary>
    public decimal Totprextr { get; set; }

    /// <summary>
    /// Estado del Descuento
    /// </summary>
    public bool Flgdes { get; set; }

    /// <summary>
    /// Tipo del Descuento 0=Sin Descuento 1 = Monto, 2= Porcentaje
    /// </summary>
    public byte Tipdes { get; set; }

    /// <summary>
    /// Flag de confirmacion del Servicio
    /// </summary>
    public bool Flgcnfirm { get; set; }

    /// <summary>
    /// Fecha de confirmacion del servicio
    /// </summary>
    public DateOnly Fchcnfirm { get; set; }

    public byte Mesinifac { get; set; }

    public int Yerinifac { get; set; }

    public byte Cntmescor { get; set; }

    public byte Mesant { get; set; }

    /// <summary>
    /// Numero NISS (ELECTRICIDAD)
    /// </summary>
    public int? Nuniss { get; set; }

    /// <summary>
    /// Flag pago de comision (1 = Sin pago, 2= En proceso de Pago, 4= Pagado)
    /// </summary>
    public byte Flgpagcom { get; set; }

    /// <summary>
    /// Fecha de pago de comision
    /// </summary>
    public DateOnly? Fchpagcom { get; set; }

    public int? Idepagcomven { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    public bool? Flgprcimpdes { get; set; }

    /// <summary>
    /// porcentaje o Importe de Descuento
    /// </summary>
    public decimal? Prcimpdes { get; set; }

    /// <summary>
    /// Cantidad de Servicios Adicionales
    /// </summary>
    public short Cntsrvadi { get; set; }

    /// <summary>
    /// Número de Faja (Identificador del servicio en Campo)
    /// </summary>
    public string Numfaj { get; set; }

    /// <summary>
    /// Numero del Poste de Luz - Asignación
    /// </summary>
    public string Numpte { get; set; }

    /// <summary>
    /// Tipo de Cliente 0=Normal, 1 = Ilegal, 2= Pasa Señal
    /// </summary>
    public int Idetileg { get; set; }

    /// <summary>
    /// Dirección MAC CM - Del Cable Modem del Cliente - Medio Fisico de INTERNET
    /// </summary>
    public string Dicmaccm { get; set; }

    /// <summary>
    /// Velocidad del acceso de INTERNET 0.- Ninguno, 1.- 512 Kbps, 2.- 1 Mb, 3.- 2 Mb, 4.- 3 Mb, 5.- 5 Mb
    /// </summary>
    public int Idevdasint { get; set; }

    public DateTime? Fchiniest { get; set; }

    public bool? Primario { get; set; }

    public int? Idequipo { get; set; }

    public virtual ICollection<Detfac> Detfacs { get; set; } = new List<Detfac>();

    public virtual Mstclssrvprd IdeclssrvprdNavigation { get; set; }

    public virtual Mstcnt IdecntNavigation { get; set; }

    public virtual Mstlstpre IdelstpreNavigation { get; set; }

    public virtual Mstplavtum IdeplavtaNavigation { get; set; }

    public virtual Mstsrvprd IdesrvprdNavigation { get; set; }

    public virtual ICollection<Mstncraut> Mstncrauts { get; set; } = new List<Mstncraut>();

    public virtual ICollection<Mstspdido> Mstspdidos { get; set; } = new List<Mstspdido>();

    public virtual Mstsrvprd Mstsrvprd { get; set; }

    public virtual ICollection<Mstvalfac> Mstvalfacs { get; set; } = new List<Mstvalfac>();
}