// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Detalle de la factura
/// </summary>
public partial class Detfac
{
    /// <summary>
    /// Id interno
    /// </summary>
    public int Idedetfac { get; set; }

    /// <summary>
    /// Id de la factura
    /// </summary>
    public int Idefac { get; set; }

    /// <summary>
    /// Id del detalle del contrato
    /// </summary>
    public int? Idedetcnt { get; set; }

    public int Ideclssrvprd { get; set; }

    public int Idesrvprd { get; set; }

    /// <summary>
    /// Identity de las CIAS o Compañias
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Cantidad de Productos Facturada
    /// </summary>
    public int Cntprd { get; set; }

    /// <summary>
    /// Pporcentaje de Descuento del Servicio
    /// </summary>
    public int Prcentdes { get; set; }

    /// <summary>
    /// Monto de Descuento del Servicio Local
    /// </summary>
    public decimal Desctoloc { get; set; }

    /// <summary>
    /// Monto de Decuento del Servicio Foraneo
    /// </summary>
    public decimal Desctofor { get; set; }

    /// <summary>
    /// Monto de Descuento del Servicio Xtra
    /// </summary>
    public decimal Desctoxtr { get; set; }

    /// <summary>
    /// Costo del Producto en Moneda Local
    /// </summary>
    public decimal Cstprdloc { get; set; }

    /// <summary>
    /// Costo del Producto en Moneda Foranea
    /// </summary>
    public decimal Cstprdfor { get; set; }

    /// <summary>
    /// Costo del Producto en Moneda Adicional
    /// </summary>
    public decimal Cstprdxtr { get; set; }

    /// <summary>
    /// Monto del Subtotal en Moneda Local
    /// </summary>
    public decimal Mtosubloc { get; set; }

    /// <summary>
    /// Monto del Subtotal en Moneda Foranea
    /// </summary>
    public decimal Mtosubfor { get; set; }

    /// <summary>
    /// Monto del Subtotal en Moneda Adicional
    /// </summary>
    public decimal Mtosubxtr { get; set; }

    /// <summary>
    /// Monto del Iva Local en Moneda Local
    /// </summary>
    public decimal Mtoivaloc { get; set; }

    /// <summary>
    /// Monto del Iva Local en Moneda Foranea
    /// </summary>
    public decimal Mtoivafor { get; set; }

    /// <summary>
    /// Monto del Iva Local en Moneda Adicional
    /// </summary>
    public decimal Mtoivaxtr { get; set; }

    /// <summary>
    /// Monto Total en Moneda Local
    /// </summary>
    public decimal Mtototloc { get; set; }

    /// <summary>
    /// Monto Total en Moneda Foranea
    /// </summary>
    public decimal Mtototfor { get; set; }

    /// <summary>
    /// Monto Total en Moneda Adicional
    /// </summary>
    public decimal Mtototxtr { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Número de Clase de Descuento
    /// </summary>
    public byte? Numclsncr { get; set; }

    /// <summary>
    /// Tasa de Cambio Oficial, moneda foranea.
    /// </summary>
    public decimal? Tascamf { get; set; }

    public virtual Mstclssrvprd IdeclssrvprdNavigation { get; set; }

    public virtual Detcnt IdedetcntNavigation { get; set; }

    public virtual Mstfac IdefacNavigation { get; set; }

    public virtual Mstsrvprd IdesrvprdNavigation { get; set; }
}