// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Detmovimiento
{
    public int Idmovimiento { get; set; }

    public int Linea { get; set; }

    public int? Idequipo { get; set; }

    public string Ns { get; set; }

    public string Mac { get; set; }

    public string Dsn { get; set; }

    public int Idmarca { get; set; }

    public int Idmodelo { get; set; }

    public int Estado { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public int? Caja { get; set; }

    public virtual Mstmovimiento IdmovimientoNavigation { get; set; }
}