// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Detalle de los servicios que se cobraran anticipados.
/// </summary>
public partial class Detplavtasrv
{
    /// <summary>
    /// Id Interno.
    /// </summary>
    public int Idekey { get; set; }

    public int? Ideplavta { get; set; }

    /// <summary>
    /// Id del detalle del plan de venta.
    /// </summary>
    public int Idedetplavta { get; set; }

    /// <summary>
    /// Id de la clase de servicio a cobrar
    /// </summary>
    public int Ideclssrvprd { get; set; }

    /// <summary>
    /// Id del servicio a cobrar
    /// </summary>
    public int Idesrvprd { get; set; }

    /// <summary>
    /// Criterio del pago (1=Pago Inmediato,2=Pago sig. figura,4 = Financiacion)
    /// </summary>
    public byte Cripag { get; set; }

    /// <summary>
    /// Numeros de cuotas en el caso que fuera un financiamiento.
    /// </summary>
    public short Numcuotas { get; set; }

    /// <summary>
    /// Monto del Cargo
    /// </summary>
    public decimal Mtocgo { get; set; }

    /// <summary>
    /// Id de la moneda del cargo inicial
    /// </summary>
    public int Idemon { get; set; }

    /// <summary>
    /// Identity de las CIAS o Compañias
    /// </summary>
    public int Idecia { get; set; }

    public string Creusr { get; set; }

    public DateTime Crefch { get; set; }

    public string Modusr { get; set; }

    public DateTime Modfch { get; set; }

    public string Creips { get; set; }

    public string Crehsn { get; set; }

    public string Modips { get; set; }

    public string Modhsn { get; set; }

    public virtual Mstclssrvprd IdeclssrvprdNavigation { get; set; }

    public virtual Detplavtum IdedetplavtaNavigation { get; set; }

    public virtual Mstsrvprd IdesrvprdNavigation { get; set; }
}