// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Detprefac
{
    public int Idedetprefac { get; set; }

    public int Ideprefac { get; set; }

    public int Idesrvprd { get; set; }

    public int Idelstpre { get; set; }

    public int Idemon { get; set; }

    public decimal Precioloc { get; set; }

    public decimal Subtotloc { get; set; }

    public decimal Dsctotloc { get; set; }

    public decimal Ivaloc { get; set; }

    public decimal Mtototloc { get; set; }

    public decimal Preciodol { get; set; }

    public decimal Subtotdol { get; set; }

    public decimal Dsctotdol { get; set; }

    public decimal Ivadol { get; set; }

    public decimal Mtototdol { get; set; }

    public int Cantidad { get; set; }
}