// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Relacion entre el Plan de Venta, Servicios y Productos y Ordenes
/// </summary>
public partial class Detplavtaord
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idekey { get; set; }

    public int? Ideplavta { get; set; }

    /// <summary>
    /// Id del plan de venta
    /// </summary>
    public int Idedetplavta { get; set; }

    /// <summary>
    /// Id de la clase de orden
    /// </summary>
    public int Ideclsord { get; set; }

    /// <summary>
    /// Id de la orden
    /// </summary>
    public int Ideord { get; set; }

    /// <summary>
    /// Identity de las CIAS o Compañias
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    public virtual Detplavtum IdedetplavtaNavigation { get; set; }
}