// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Detalle del plan de Venta
/// </summary>
public partial class Detplavtum
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idedetplavta { get; set; }

    /// <summary>
    /// Id del Plan de Venta
    /// </summary>
    public int Ideplavta { get; set; }

    /// <summary>
    /// Id de la clase del servicio
    /// </summary>
    public int Ideclssrvprd { get; set; }

    /// <summary>
    /// Id del servicio
    /// </summary>
    public int Idesrvprd { get; set; }

    /// <summary>
    /// Identity de las CIAS o Compañias
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Cantidad de Ciclo a Repetir
    /// </summary>
    public int Cntclo { get; set; }

    /// <summary>
    /// Numero de cuotas en caso que se financiado
    /// </summary>
    public short Numcuotas { get; set; }

    /// <summary>
    /// Criterio de Pago (1=Pago en Efectivo, 2= Pago sig. Facturacion, 4 =Financiado)
    /// </summary>
    public byte Cripag { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    public int Idelstpre { get; set; }

    public virtual ICollection<Detplavtaord> Detplavtaords { get; set; } = new List<Detplavtaord>();

    public virtual ICollection<Detplavtasrv> Detplavtasrvs { get; set; } = new List<Detplavtasrv>();

    public virtual Mstclssrvprd IdeclssrvprdNavigation { get; set; }

    public virtual Mstplavtum IdeplavtaNavigation { get; set; }

    public virtual Mstsrvprd IdesrvprdNavigation { get; set; }
}