// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Detalle de las ordes que estan asociadas a un servicio
/// </summary>
public partial class Detsrvord
{
    public int Idekey { get; set; }

    /// <summary>
    /// Id del Servicio
    /// </summary>
    public int Idesrvprd { get; set; }

    /// <summary>
    /// Id de la Clase de Orden
    /// </summary>
    public int Ideclsord { get; set; }

    /// <summary>
    /// Id de la Orden
    /// </summary>
    public int Ideord { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Id de la Compañia.
    /// </summary>
    public int? Idecia { get; set; }

    public virtual Mstsrvprd IdesrvprdNavigation { get; set; }
}