// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Facturas no generadas durante proceso de registro de nuevo contrato, especificamente las facturas de instalacion auto generadas.
/// </summary>
public partial class Facnogeneradum
{
    public int IdfacturaNoGen { get; set; }

    public int Idsucursal { get; set; }

    public int Idcontrato { get; set; }

    public int IddetalleContrato { get; set; }

    public int Idservicio { get; set; }

    public string Cliente { get; set; }

    public DateOnly Fecha { get; set; }

    public bool Reportada { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime FechaRegistro { get; set; }
}