// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class FacturasCobrada
{
    public int IdCnt { get; set; }

    public DateOnly? MesFac { get; set; }

    public int? IdCli { get; set; }

    public int? NºCnt { get; set; }

    public string Sucursal { get; set; }

    public string Colector { get; set; }

    public string Zona { get; set; }

    public string EstadoCnt { get; set; }

    public string Tecnol { get; set; }

    public string Marca { get; set; }

    public string Servicio { get; set; }

    public byte? DiaPago { get; set; }

    public DateOnly? FchPago { get; set; }

    public string Origen { get; set; }
}