// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class FacturasPagosCliente
{
    public int Idefac { get; set; }

    public string Srefac { get; set; }

    public int Idecnt { get; set; }

    public int Idecli { get; set; }

    public DateOnly MesFactura { get; set; }

    public string Cancelada { get; set; }

    public string TipoFactura { get; set; }

    public DateOnly? Fchanu { get; set; }

    public string Obsanu { get; set; }

    public string EstadoFactura { get; set; }

    public DateOnly? FchPago { get; set; }

    public string Vendedor { get; set; }

    public string Colector { get; set; }

    public string _ { get; set; }

    public DateOnly? FchRoc { get; set; }

    public string HoraPago { get; set; }

    public int? DiaPagoMes { get; set; }

    public string DiaSemana { get; set; }

    public DateOnly? MesRoc { get; set; }

    public string TipoTrCaja { get; set; }

    public string EstadoRoc { get; set; }

    public string Sertracaj { get; set; }

    public string FormaPago { get; set; }

    public string Tipo { get; set; }

    public string Dsccaj { get; set; }

    public string Tipocaja { get; set; }

    public string EstadoCnt { get; set; }

    public string Sucursal { get; set; }

    public string Ciudad { get; set; }

    public string ClaseSrv { get; set; }

    public string TipoSrv { get; set; }

    public string Servicios { get; set; }

    public string ServiciosNoTv { get; set; }

    public long? Fila { get; set; }
}