// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Hisgenfac
{
    public int Idehisgenfac { get; set; }

    public int Idecia { get; set; }

    public int? Idecatcli { get; set; }

    public int? Idesuc { get; set; }

    public int? Idedep { get; set; }

    public int? Idemun { get; set; }

    public int? Idezon { get; set; }

    public int? Ideszn { get; set; }

    public DateTime Fchcorfac { get; set; }
}