// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Hstfacxtr
{
    public int Idproceso { get; set; }

    public int Idfacxtr { get; set; }

    public int? Idfac { get; set; }

    public DateTime Fchproceso { get; set; }

    public int Aplicada { get; set; }

    public string Resultado { get; set; }

    public string Valores { get; set; }
}