// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ModeloPrincipal.Entity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ModeloPrincipal.Entity
{
    public partial interface ICVGEntitiesProcedures
    {
        Task<List<spObtenerContratosDisponiblesResult>> spObtenerContratosDisponiblesAsync(int? iDEUSUARIO, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spObtenerFacturasColectorResult>> spObtenerFacturasColectorAsync(int? idUsuario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
