// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Inverseguro
{
    public int Id { get; set; }

    public decimal MonthlyPayment { get; set; }

    public byte? DueDate { get; set; }

    public int? Antiguedad { get; set; }

    public int HouseValue { get; set; }

    public string PaymentMethod { get; set; }

    public string Internet { get; set; }

    public int? NumberTv { get; set; }

    public int? Age { get; set; }

    public string Sex { get; set; }

    public int? Delinquent { get; set; }

    public int? AverageDay { get; set; }

    public int AverageDay2 { get; set; }

    public string Nodo { get; set; }

    public string Barrio { get; set; }

    public string CodigoBarrio { get; set; }

    public string Servicio2 { get; set; }

    public int? Pm { get; set; }

    public int? Activo { get; set; }

    public string Default { get; set; }
}