// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class LastCheckedConsecutive
{
    public int? TableId { get; set; }

    public int? LastConsecutiveValue { get; set; }

    public DateTime? LastCheckDate { get; set; }
}