// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Tabla para el registro del envio de los avisos de cobro o factura digital correspondientes al mes en curso.
/// </summary>
public partial class LogEnvioFacturaDigital
{
    public int Idcontrato { get; set; }

    public int NoContrato { get; set; }

    public int Idsucursal { get; set; }

    public int Idfactura { get; set; }

    public string Serie { get; set; }

    public string NoFactura { get; set; }

    public string Periodo { get; set; }

    public string Cliente { get; set; }

    public string Correo { get; set; }

    public bool Procesada { get; set; }

    public DateTime? FechaProceso { get; set; }
}