// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstapefac
{
    /// <summary>
    /// Identity del la tabla MSTAPEFAC
    /// </summary>
    public int Ideapefac { get; set; }

    public int Idecia { get; set; }

    /// <summary>
    /// Estado de la Apertura (0=Cerrada,1=Abierta)
    /// </summary>
    public bool Stdapefac { get; set; }

    /// <summary>
    /// Fecha de Apertura de la Generacion de la Factura
    /// </summary>
    public DateTime Fchiniape { get; set; }

    /// <summary>
    /// Fecha de Cierre de la Generacion de la Factura
    /// </summary>
    public DateTime Fchfinape { get; set; }

    public byte Mesfac { get; set; }

    public int Year { get; set; }

    public DateTime Crefch { get; set; }

    public DateTime Modfch { get; set; }

    public string Creusr { get; set; }

    public string Modusr { get; set; }

    public string Creips { get; set; }

    public string Crehsn { get; set; }

    public string Modips { get; set; }

    public string Modhsn { get; set; }

    public virtual ICollection<Mstfac> Mstfacs { get; set; } = new List<Mstfac>();

    public virtual ICollection<Mstvalfac> Mstvalfacs { get; set; } = new List<Mstvalfac>();
}