// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Clase de Créditos Automáticos
/// </summary>
public partial class Mstclsncraut
{
    /// <summary>
    /// Identity de Clase de Créditos Automáticos
    /// </summary>
    public int Ideclsncraut { get; set; }

    public int Idecia { get; set; }

    /// <summary>
    /// Número de Clase de Descuento
    /// </summary>
    public byte Numclsncr { get; set; }

    public string Dscnumclsncr { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Configuración Contable del Descuento Sobre Venta  (1= Cta Contable, 2 = Patrón de Cuenta)
    /// </summary>
    public byte Cnfctadsc { get; set; }

    /// <summary>
    /// Cuenta Contable del Descuento s/ Venta (Ingreso)
    /// </summary>
    public int? Idectadscvta { get; set; }

    /// <summary>
    /// Patron Contable de Descuento s/ Venta - Segmento 1
    /// </summary>
    public int? Patctadscvta { get; set; }

    public virtual ICollection<Mstncraut> Mstncrauts { get; set; } = new List<Mstncraut>();
}