// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Clase de Servicios
/// </summary>
public partial class Mstclssrvprd
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Ideclssrvprd { get; set; }

    /// <summary>
    /// Identity de la Compañía
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Código de Clase de Servicio / Producto
    /// </summary>
    public string Codclssrvprd { get; set; }

    /// <summary>
    /// Descripción de la Clase de Servicio o Producto
    /// </summary>
    public string Dscclssrvprd { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Flag que indica si la clase de servicio contendrá servicios principales (0 - No, 1-Si)
    /// </summary>
    public bool Flgsrvpri { get; set; }

    public int Internet { get; set; }

    public int? Idvlan { get; set; }

    public string CuentaContable { get; set; }

    public virtual ICollection<Detcnt> Detcnts { get; set; } = new List<Detcnt>();

    public virtual ICollection<Detfac> Detfacs { get; set; } = new List<Detfac>();

    public virtual ICollection<Detplavtum> Detplavta { get; set; } = new List<Detplavtum>();

    public virtual ICollection<Detplavtasrv> Detplavtasrvs { get; set; } = new List<Detplavtasrv>();

    public virtual ICollection<Mstlstpre> Mstlstpres { get; set; } = new List<Mstlstpre>();

    public virtual ICollection<Mstsrvprd> Mstsrvprds { get; set; } = new List<Mstsrvprd>();
}