// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Catalogo maestro de cuadrillas de trabajo
/// </summary>
public partial class Mstcuadrilla
{
    public int Idcuadrilla { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    /// <summary>
    /// Contrata o Fija
    /// </summary>
    public string Tipo { get; set; }

    public string Placa { get; set; }

    public int Idsucursal { get; set; }

    public string Bodega { get; set; }

    public DateTime FechaRegistro { get; set; }

    public bool Activo { get; set; }

    public int? MaxCpeAsignados { get; set; }
}