// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Contratos
/// </summary>
public partial class Mstcnt
{
    /// <summary>
    /// Id Interno del Contrato
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Id de la compñia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Id del Cliente
    /// </summary>
    public int Idecli { get; set; }

    /// <summary>
    /// Numero del contrato (Pre-numerado)
    /// </summary>
    public int Ideftocnt { get; set; }

    /// <summary>
    /// Id del Agente (Del tipo vendedor)
    /// </summary>
    public int Ideagente { get; set; }

    /// <summary>
    /// Fecha de Firma del Contrato
    /// </summary>
    public DateOnly Fchfma { get; set; }

    /// <summary>
    /// Fecha de Inicio del Contrato
    /// </summary>
    public DateOnly Fchini { get; set; }

    /// <summary>
    /// Fecha Final del Contrato
    /// </summary>
    public DateOnly Fchfin { get; set; }

    /// <summary>
    /// Id de la sucursal
    /// </summary>
    public int Idesuc { get; set; }

    /// <summary>
    /// Id del departamento
    /// </summary>
    public int Idedep { get; set; }

    /// <summary>
    /// Id del Municipio
    /// </summary>
    public int Idemun { get; set; }

    /// <summary>
    /// Id de la Zona
    /// </summary>
    public int Idezon { get; set; }

    /// <summary>
    /// Id de la Sub-Zona
    /// </summary>
    public int Ideszn { get; set; }

    /// <summary>
    /// Direccion de Cobro del Contrato
    /// </summary>
    public string Dircob010 { get; set; }

    /// <summary>
    /// Direccion de Cobro del Contrato
    /// </summary>
    public string Dircob020 { get; set; }

    /// <summary>
    /// Nombre a quien se facturara
    /// </summary>
    public string Nomfac { get; set; }

    /// <summary>
    /// Flag que indica si el contrato pagará por debito automático
    /// </summary>
    public bool Flgdeb { get; set; }

    /// <summary>
    /// Moneda en que se debitará
    /// </summary>
    public byte? Mondeb { get; set; }

    /// <summary>
    /// Id del Emisor de la tarjeta
    /// </summary>
    public int? Ideemitar { get; set; }

    /// <summary>
    /// Nombre del tarjetahabiente
    /// </summary>
    public string Nomtar { get; set; }

    /// <summary>
    /// Numero de la tarjeta
    /// </summary>
    public string Numtar { get; set; }

    /// <summary>
    /// Mes que vence la tarjeta
    /// </summary>
    public short? Mesventar { get; set; }

    /// <summary>
    /// Año en que vence la tarjeta
    /// </summary>
    public short? Yerventar { get; set; }

    /// <summary>
    /// Id del Grupo de Clientes
    /// </summary>
    public int Idetipcon { get; set; }

    /// <summary>
    /// Codigo del Estado Financiero del Contrato.
    /// </summary>
    public string Codestfin { get; set; }

    /// <summary>
    /// Id del motivo de anulación
    /// </summary>
    public int? Idemvoanu { get; set; }

    /// <summary>
    /// Fecha de Anulación
    /// </summary>
    public DateTime? Fchanu { get; set; }

    /// <summary>
    /// Observacion de la Anulacion
    /// </summary>
    public string Obsanu { get; set; }

    /// <summary>
    /// Observacion del contrato
    /// </summary>
    public string Obscnt { get; set; }

    /// <summary>
    /// monto SubTotal de Precios del Servicio o Productos Local
    /// </summary>
    public decimal Mtosubpreloc { get; set; }

    /// <summary>
    /// Monto IVA Local
    /// </summary>
    public decimal Mtoivaloc { get; set; }

    /// <summary>
    /// Monto de Descuento Local
    /// </summary>
    public decimal Mtodesloc { get; set; }

    /// <summary>
    /// Monto del Contrato local
    /// </summary>
    public decimal Mtocntloc { get; set; }

    /// <summary>
    /// Monto SubTotal de Precios del Servicio o producto Foraneo
    /// </summary>
    public decimal Mtosubprefor { get; set; }

    /// <summary>
    /// Monto de IVA Foraneo
    /// </summary>
    public decimal Mtoivafor { get; set; }

    /// <summary>
    /// Monto de Descuento Foraneo
    /// </summary>
    public decimal Mtodesfor { get; set; }

    /// <summary>
    /// Monto del Contrato Foraneo
    /// </summary>
    public decimal Mtocntfor { get; set; }

    /// <summary>
    /// Monto Subtotal de Precios del Servicioo Producto Extra
    /// </summary>
    public decimal Mtosubprxtr { get; set; }

    /// <summary>
    /// Monto IVA Extra
    /// </summary>
    public decimal Mtoivaxtr { get; set; }

    /// <summary>
    /// Monto de Descuento Extra
    /// </summary>
    public decimal Mtodesxtr { get; set; }

    /// <summary>
    /// Monto del Contrato Extra
    /// </summary>
    public decimal Mtocntxtr { get; set; }

    /// <summary>
    /// Dia de Pago.
    /// </summary>
    public byte? Diapag { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Flag que indica si el dia de pago fue acordado por el cliente (0= Calculado por sistema, 1 = Definido por el Cliente)
    /// </summary>
    public bool? Flgdiapag { get; set; }

    public int? Idtecnologia { get; set; }

    public int? Idequipo { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public int? IdestadoContrato { get; set; }

    public DateTime? FechaUltEstado { get; set; }

    public virtual ICollection<Detcnt> Detcnts { get; set; } = new List<Detcnt>();

    public virtual ICollection<Mstfac> Mstfacs { get; set; } = new List<Mstfac>();

    public virtual ICollection<Mstncraut> Mstncrauts { get; set; } = new List<Mstncraut>();

    public virtual ICollection<Mstspdido> Mstspdidos { get; set; } = new List<Mstspdido>();

    public virtual ICollection<Mstticket> Msttickets { get; set; } = new List<Mstticket>();

    public virtual ICollection<Mstvalfac> Mstvalfacs { get; set; } = new List<Mstvalfac>();
}