// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Clientes
/// </summary>
public partial class Mstcli
{
    /// <summary>
    /// Id Interno del Cliente
    /// </summary>
    public int Idecli { get; set; }

    /// <summary>
    /// Id de la Compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Id de la categoria del cliente
    /// </summary>
    public int Idecatcli { get; set; }

    /// <summary>
    /// Id el tipo de persona
    /// </summary>
    public int Idetipper { get; set; }

    /// <summary>
    /// Nombre del Cliente
    /// </summary>
    public string Nomcli { get; set; }

    /// <summary>
    /// Apellido 1 del Cliente
    /// </summary>
    public string Apecli1 { get; set; }

    /// <summary>
    /// Apellido 2 del Cliente
    /// </summary>
    public string Apecli2 { get; set; }

    /// <summary>
    /// Id del tipo de documento de Identidad
    /// </summary>
    public int Idedocide { get; set; }

    /// <summary>
    /// Numero del Documento de Identidad
    /// </summary>
    public string Numdocide { get; set; }

    /// <summary>
    /// Id de la Sucursal
    /// </summary>
    public int Idesuc { get; set; }

    /// <summary>
    /// Id del departamento
    /// </summary>
    public int Idedep { get; set; }

    /// <summary>
    /// Id del municipio
    /// </summary>
    public int Idemun { get; set; }

    /// <summary>
    /// Id de la Zona
    /// </summary>
    public int Idezon { get; set; }

    /// <summary>
    /// Id de la Sub Zona
    /// </summary>
    public int Ideszn { get; set; }

    /// <summary>
    /// Direccion del Cliente
    /// </summary>
    public string Dircli010 { get; set; }

    public string Dircli020 { get; set; }

    /// <summary>
    /// Telefono del cliente
    /// </summary>
    public string Telcli { get; set; }

    /// <summary>
    /// Celular del Cliente
    /// </summary>
    public string Celcli { get; set; }

    /// <summary>
    /// Fax del Cliente
    /// </summary>
    public string Faxcli { get; set; }

    /// <summary>
    /// Lugar de Trabajo del Cliente
    /// </summary>
    public string Lugtra { get; set; }

    /// <summary>
    /// Telefono del Trabajo del cliente
    /// </summary>
    public string Teltra { get; set; }

    /// <summary>
    /// Fax del Trabajo del Cliente
    /// </summary>
    public string Faxtra { get; set; }

    /// <summary>
    /// Correo electrónico del cliente 1
    /// </summary>
    public string Email1 { get; set; }

    /// <summary>
    /// Correo electrónico del cliente 2
    /// </summary>
    public string Email2 { get; set; }

    /// <summary>
    /// Flag que indica si el Cliente es Excento del Iva
    /// </summary>
    public bool Etoiva { get; set; }

    /// <summary>
    /// Numero del documento de exoneración
    /// </summary>
    public string Docetoiva { get; set; }

    /// <summary>
    /// Fecha que Vence la exoneracion
    /// </summary>
    public DateTime? Fchveneto { get; set; }

    /// <summary>
    /// Representante Legal
    /// </summary>
    public string Repleg { get; set; }

    /// <summary>
    /// Observación
    /// </summary>
    public string Obscli { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Identity de Cuenta por Cobrar
    /// </summary>
    public int? Idectacxc { get; set; }

    /// <summary>
    /// Identity de Cuenta Contable de Cuentas por Cobrar Incobrable
    /// </summary>
    public int? Idectacxcinc { get; set; }

    /// <summary>
    /// Patron Contable de Cuenta x Cobrar - Segmento 1
    /// </summary>
    public string Patctacxc { get; set; }

    /// <summary>
    /// Patron Contable de Cuenta x Cobrar - Incobrable - Segmento 1
    /// </summary>
    public string Patctacxcinc { get; set; }

    /// <summary>
    /// Patron Contable de Ingresos por Ventas - Segmento 1
    /// </summary>
    public string Patctavta { get; set; }

    /// <summary>
    /// Id Cuenta Contable de Ingresos por Ventas de Contado
    /// </summary>
    public int? Idectavtacon { get; set; }

    /// <summary>
    /// Patron Contable de Ingresos por Ventas de Contado - Segmento 1
    /// </summary>
    public string Patctavtacon { get; set; }

    public string Sexo { get; set; }

    public DateOnly? Fchnac { get; set; }

    public virtual Mstubigeo IdedepNavigation { get; set; }

    public virtual Mstubigeo IdemunNavigation { get; set; }

    public virtual Mstsuc IdesucNavigation { get; set; }

    public virtual Mstubigeo IdesznNavigation { get; set; }

    public virtual Mstubigeo IdezonNavigation { get; set; }

    public virtual ICollection<Mstfac> Mstfacs { get; set; } = new List<Mstfac>();

    public virtual ICollection<Mstncraut> Mstncrauts { get; set; } = new List<Mstncraut>();

    public virtual ICollection<Mstvalfac> Mstvalfacs { get; set; } = new List<Mstvalfac>();
}