// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstdesactivfac
{
    public int Iddesactivacion { get; set; }

    public int Idsucursal { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime FechaFin { get; set; }

    public string Observaciones { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime FechaRegistro { get; set; }
}