// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstequipo
{
    public int Idequipo { get; set; }

    public string Mac { get; set; }

    public string NumeroSeriePon { get; set; }

    public int? Idtipo { get; set; }

    public int Idmarca { get; set; }

    public int Idmodelo { get; set; }

    public int Instalado { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string Usuario { get; set; }

    public int? Idcontrato { get; set; }

    public string Dsn { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string Bodega { get; set; }

    public int? Origen { get; set; }

    public int? IdestadoCpe { get; set; }

    public int? IddetalleContrato { get; set; }

    public bool? Administrado { get; set; }

    public virtual Mstmodelo Mstmodelo { get; set; }
}