// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de factura
/// </summary>
public partial class Mstfac
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idefac { get; set; }

    /// <summary>
    /// Identity de la Compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Identity de la Moneda
    /// </summary>
    public int Idemon { get; set; }

    /// <summary>
    /// Numero Fiscal de la Factura
    /// </summary>
    public int Numfisfac { get; set; }

    /// <summary>
    /// Serie de Factura
    /// </summary>
    public string Srefac { get; set; }

    /// <summary>
    /// Id del Contrato
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Identity del Cliente
    /// </summary>
    public int Idecli { get; set; }

    /// <summary>
    /// Agente de la Factura para Cobro
    /// </summary>
    public int Ideagente { get; set; }

    /// <summary>
    /// Fecha de la Factura
    /// </summary>
    public DateOnly Fchini { get; set; }

    /// <summary>
    /// Fecha de Vencimiento de la Factura
    /// </summary>
    public DateOnly Fchven { get; set; }

    /// <summary>
    /// Mes de Factura.
    /// </summary>
    public byte Mesfac { get; set; }

    /// <summary>
    /// Año de Factura
    /// </summary>
    public int Yerfac { get; set; }

    /// <summary>
    /// Estado de la Factura. A = ABONADO. C=CANCELADO. S=SIN ABONO
    /// </summary>
    public string Codsts { get; set; }

    /// <summary>
    /// Estatus de la Vigencia.  C=CORRIENTE, V=VENCIDA
    /// </summary>
    public string Persts { get; set; }

    /// <summary>
    /// La Factura es de crédito? 0 = Contado, 1 = Crédito
    /// </summary>
    public bool Flgtipfac { get; set; }

    /// <summary>
    /// Monto Total de Descuento Local
    /// </summary>
    public decimal Mtodesfacloc { get; set; }

    /// <summary>
    /// Sub total de la factura en moneda Local
    /// </summary>
    public decimal Subfacloc { get; set; }

    /// <summary>
    /// Iva de la factura en moneda Local
    /// </summary>
    public decimal Ivafacloc { get; set; }

    /// <summary>
    /// Monto de la factura en moneda Local
    /// </summary>
    public decimal Mtofacloc { get; set; }

    /// <summary>
    /// Saldo de Factura en Moneda Local
    /// </summary>
    public decimal Sdofacloc { get; set; }

    /// <summary>
    /// Monto Total de Descuento Dolares
    /// </summary>
    public decimal Mtodesfacfor { get; set; }

    /// <summary>
    /// Sub total de la factura en moneda Foranea
    /// </summary>
    public decimal Subfacfor { get; set; }

    /// <summary>
    /// Iva de la factura en moneda Foranea
    /// </summary>
    public decimal Ivafacfor { get; set; }

    /// <summary>
    /// Monto de la factura en moneda Foranea
    /// </summary>
    public decimal Mtofacfor { get; set; }

    /// <summary>
    /// Saldo de Factura en Moneda Foraneo
    /// </summary>
    public decimal Sdofacfor { get; set; }

    /// <summary>
    /// Monto Total de Descuento Xtra
    /// </summary>
    public decimal Mtodesfacxtr { get; set; }

    /// <summary>
    /// Subtotal de la Factura en Moneda Adicional
    /// </summary>
    public decimal Subfacxtr { get; set; }

    /// <summary>
    /// IVA de la Factura en Moneda Adicional
    /// </summary>
    public decimal Ivafacxtr { get; set; }

    /// <summary>
    /// Monto de la Factura en Moneda Adicional
    /// </summary>
    public decimal Mtofacxtr { get; set; }

    /// <summary>
    /// Saldo de Factura en Moneda Adicional
    /// </summary>
    public decimal? Sdofacxtr { get; set; }

    /// <summary>
    /// Id del motivo de anulacion
    /// </summary>
    public int? Idemvoanu { get; set; }

    /// <summary>
    /// Fecha de anulacion de la factura
    /// </summary>
    public DateOnly? Fchanu { get; set; }

    /// <summary>
    /// Observacion de la anulacion.
    /// </summary>
    public string Obsanu { get; set; }

    /// <summary>
    /// Estado de la Fac. 1 Generada, 2 Impresa, 3 Anulada
    /// </summary>
    public byte Stdfac { get; set; }

    /// <summary>
    /// Fecha de Cancelación de la Factura
    /// </summary>
    public DateOnly? Fchcan { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    public int? Ideapefac { get; set; }

    /// <summary>
    /// Identity del Colector a la cual fue asignada la factura
    /// </summary>
    public int? Idecolector { get; set; }

    /// <summary>
    /// Identity del Colector que Cobro la factura.
    /// </summary>
    public int? Idecobrador { get; set; }

    /// <summary>
    /// Fecha que se asigno al colector
    /// </summary>
    public DateOnly? Fchasicol { get; set; }

    /// <summary>
    /// Identity del Asiento Contable
    /// </summary>
    public int? Ideasi { get; set; }

    /// <summary>
    /// Identity del Periodo Contable
    /// </summary>
    public int? Idepdo { get; set; }

    /// <summary>
    /// Mes Fiscal
    /// </summary>
    public int Mesfis { get; set; }

    /// <summary>
    /// Año Fiscal
    /// </summary>
    public int Yerfis { get; set; }

    /// <summary>
    /// Identity del Estado Contable
    /// </summary>
    public int? Ideestcon { get; set; }

    /// <summary>
    /// Flag de Cuenta por Cobrar - Incobrables
    /// </summary>
    public bool Flgcxcinc { get; set; }

    /// <summary>
    /// Identity del Detalle del Periodo Contable
    /// </summary>
    public int? Iddpdo { get; set; }

    /// <summary>
    /// Fecha en la que el saldo de la factura es considerado como cuenta incobrable.
    /// </summary>
    public DateOnly? Fchcxcinc { get; set; }

    /// <summary>
    ///  Identity del Asiento Contable de la Cuenta Incobrable
    /// </summary>
    public int? Ideasicxcinc { get; set; }

    /// <summary>
    /// Identity del Periodo Contable de la Cuenta Incobrable
    /// </summary>
    public int? Idepdocxcinc { get; set; }

    /// <summary>
    /// Identity del Detalle del Periodo Contable de la Cuenta Incobrable
    /// </summary>
    public int? Iddpdocxcinc { get; set; }

    /// <summary>
    /// Mes Fiscal de la Cuenta Incobrable
    /// </summary>
    public int Mesfiscxcinc { get; set; }

    /// <summary>
    /// Año Fiscal de la Cuenta Incobrable
    /// </summary>
    public int Yerfiscxcinc { get; set; }

    /// <summary>
    /// Identity del Estado Contable de las Cuenta Incobrable
    /// </summary>
    public int? Istconcxcinc { get; set; }

    /// <summary>
    /// Tasa de Cambio Oficial, moneda foranea.
    /// </summary>
    public decimal? Tascamf { get; set; }

    /// <summary>
    /// Indicador o Bandera del estado de la factura (0=No Impresa, 1=Impresa)
    /// </summary>
    public bool? Flgindimp { get; set; }

    /// <summary>
    /// Código de Barra de la factura impresa mensual, compuesto por la serie de factura mas el numero del sistema.
    /// </summary>
    public string Codbarra { get; set; }

    /// <summary>
    /// Bandera o Indicador de la factura del cliente si esta fue impresa (0.- No impresa, 1.- Impresa).
    /// </summary>
    public bool? Flgfacimp { get; set; }

    public virtual ICollection<Detfac> Detfacs { get; set; } = new List<Detfac>();

    public virtual Mstapefac IdeapefacNavigation { get; set; }

    public virtual Mstcli IdecliNavigation { get; set; }

    public virtual Mstcnt IdecntNavigation { get; set; }
}