// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstformato
{
    public int Idformato { get; set; }

    public string Descripcion { get; set; }

    public int Idelibfac { get; set; }
}