// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Registro de Facturacion Extraordinaria
/// </summary>
public partial class Mstfacxtr
{
    public int IdfacturaXtra { get; set; }

    public int Idcontrato { get; set; }

    public int Idprecio { get; set; }

    public int Idservicio { get; set; }

    public int FlagPermanente { get; set; }

    public int? MesIniAplicacion { get; set; }

    public int? AñoIniAplicacion { get; set; }

    public int? MesFinAplicacion { get; set; }

    public int? AñoFinAplicacion { get; set; }

    public int Cantidad { get; set; }

    public int? Activo { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime FechaRegistro { get; set; }
}