// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Catalogo Maestro de Integraciones
/// </summary>
public partial class Mstintegracion
{
    public int Idintegracion { get; set; }

    public int Idtecnologia { get; set; }

    public string Descripcion { get; set; }

    public string Codigo { get; set; }

    public int Prioridad { get; set; }

    public bool Activa { get; set; }

    public bool? Primario { get; set; }

    public bool? RegistraCpe { get; set; }

    public bool? AprovisionaCpe { get; set; }

    public bool? RequiereActivacion { get; set; }
}