// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de lista de precios
/// </summary>
public partial class Mstlstpre
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idelstpre { get; set; }

    /// <summary>
    /// Id de la compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Id de la categoria de cliente
    /// </summary>
    public int Idecatcli { get; set; }

    /// <summary>
    /// Id de la clase de servicio/Producto.
    /// </summary>
    public int Ideclssrvprd { get; set; }

    /// <summary>
    /// Id del servicio producto.
    /// </summary>
    public int Idesrvprd { get; set; }

    /// <summary>
    /// Id sucursal
    /// </summary>
    public int Idesuc { get; set; }

    public int Idedep { get; set; }

    public int Idemun { get; set; }

    public int Idezon { get; set; }

    public int Ideszn { get; set; }

    public int Idemon { get; set; }

    public decimal Subpre { get; set; }

    public decimal Ivapre { get; set; }

    public decimal Totpre { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    public int? Valido { get; set; }

    public int Factor { get; set; }

    public virtual ICollection<Detcnt> Detcnts { get; set; } = new List<Detcnt>();

    public virtual Mstclssrvprd IdeclssrvprdNavigation { get; set; }

    public virtual Mstubigeo IdedepNavigation { get; set; }

    public virtual Mstubigeo IdemunNavigation { get; set; }

    public virtual Mstsrvprd IdesrvprdNavigation { get; set; }

    public virtual Mstsuc IdesucNavigation { get; set; }

    public virtual Mstubigeo IdesznNavigation { get; set; }

    public virtual Mstubigeo IdezonNavigation { get; set; }
}