// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Información general de la cuenta activada de MoviTV
/// 
/// </summary>
public partial class Mstlogin
{
    public int NoContrato { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string UsuarioRegistro { get; set; }

    public bool Activado { get; set; }

    public DateTime? FechaActivacion { get; set; }
}