// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstlibfac
{
    /// <summary>
    /// Identity de libreta
    /// </summary>
    public int Idelibfac { get; set; }

    public int Idecia { get; set; }

    public string Codserfac { get; set; }

    public int Numinifac { get; set; }

    public int Numfinfac { get; set; }

    public int Ultnumfact { get; set; }

    public bool Flglibcer { get; set; }

    /// <summary>
    /// señala si la libreta sera usada en la generacion de factura
    /// </summary>
    public bool Flggenfac { get; set; }

    public bool? Flglibsys { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }
}