// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstmodelo
{
    public int Idmodelo { get; set; }

    public int Idmarca { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionCorta { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string UsuarioRegistro { get; set; }

    public bool? Aprovisiona { get; set; }

    public string Protocolo { get; set; }

    public bool? DualBand { get; set; }

    public bool? Activo { get; set; }

    public bool? SuspensionCompleta { get; set; }

    public bool? FallaEnableTv { get; set; }

    public virtual ICollection<Mstequipo> Mstequipos { get; set; } = new List<Mstequipo>();
}