// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// 1 En proceso
/// 2 Aplicado
/// 3 Cancelado
/// </summary>
public partial class Mstmovimiento
{
    public int Idmovimiento { get; set; }

    public DateOnly Fecha { get; set; }

    public string Observaciones { get; set; }

    public int IdtipoMovimiento { get; set; }

    public string BodegaOrigen { get; set; }

    public string BodegaDestino { get; set; }

    public int Estado { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public virtual ICollection<Detmovimiento> Detmovimientos { get; set; } = new List<Detmovimiento>();
}