// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Nota de Crédito Automática
/// </summary>
public partial class Mstncraut
{
    /// <summary>
    /// Identity del Detalle de Notas de Créditos Automáticas
    /// </summary>
    public int Idemstncraut { get; set; }

    public int Idecia { get; set; }

    /// <summary>
    /// Identity del Maestro de Nota de Crédito Automática
    /// </summary>
    public int Ideclsnrcaut { get; set; }

    /// <summary>
    /// Identity del Cliente
    /// </summary>
    public int Idecli { get; set; }

    /// <summary>
    /// Identity del Contrato
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Identity del Detalle del Contrato
    /// </summary>
    public int Idedetcnt { get; set; }

    /// <summary>
    /// Tipo de Nota de Crédito (1 = Porcentaje, 2 = Monto)
    /// </summary>
    public byte Tipncraut { get; set; }

    /// <summary>
    /// Importe o Porcentaje de la Nota de Crédito Automática
    /// </summary>
    public decimal Porncraut { get; set; }

    /// <summary>
    /// Fecha Inicial
    /// </summary>
    public DateOnly Fchini { get; set; }

    /// <summary>
    /// Fecha Final
    /// </summary>
    public DateOnly Fchfin { get; set; }

    /// <summary>
    /// Nota de Crédito Automática es permanente
    /// </summary>
    public bool Flgncrper { get; set; }

    /// <summary>
    /// Código de Estado de la Transacción
    /// </summary>
    public int Codesttra { get; set; }

    /// <summary>
    /// Fecha de Aprobación
    /// </summary>
    public DateOnly Fchapr { get; set; }

    /// <summary>
    /// Comentario de la Aprobación de la Nota de Crédito Automática
    /// </summary>
    public string Comncr { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    public virtual Mstcli IdecliNavigation { get; set; }

    public virtual Mstclsncraut IdeclsnrcautNavigation { get; set; }

    public virtual Mstcnt IdecntNavigation { get; set; }

    public virtual Detcnt IdedetcntNavigation { get; set; }
}