// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Origen
/// </summary>
public partial class Mstorigen
{
    /// <summary>
    /// Llave Primaria del Maestro de Origen
    /// </summary>
    public int Ideorigen { get; set; }

    /// <summary>
    /// Identity del Maestro de Compañía
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Código del Origen
    /// </summary>
    public string Codorigen { get; set; }

    /// <summary>
    /// Número de Origen
    /// </summary>
    public int Numorigen { get; set; }

    /// <summary>
    /// Consecutivo Para los Documento Asociados al Origén
    /// </summary>
    public int Consec { get; set; }

    /// <summary>
    /// Origen es Contabilidad
    /// </summary>
    public bool Flgcnt { get; set; }

    /// <summary>
    /// Origen es Banco
    /// </summary>
    public bool Flgbco { get; set; }

    /// <summary>
    /// Origen es Activo Fijo
    /// </summary>
    public bool Flgafj { get; set; }

    /// <summary>
    /// Indicador es Presupuesto
    /// </summary>
    public bool Flgpre { get; set; }

    /// <summary>
    /// Indicador de Inventario
    /// </summary>
    public bool Flginv { get; set; }

    /// <summary>
    /// Indicador de Configuración
    /// </summary>
    public bool Flgcnf { get; set; }

    /// <summary>
    /// Indicador de Cliente
    /// </summary>
    public bool Flgcli { get; set; }

    /// <summary>
    /// Indicador de Caja
    /// </summary>
    public bool Flgcaj { get; set; }

    /// <summary>
    /// Indicador de Caja
    /// </summary>
    public bool Flgfac { get; set; }

    /// <summary>
    /// Indicador de Ordenes
    /// </summary>
    public bool Flgord { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificacion
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creó el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creó el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modificó el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modificó el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Indicador de Nomina - Planilla
    /// </summary>
    public bool Flgnma { get; set; }

    /// <summary>
    /// Indicador de Marcas - Reloj
    /// </summary>
    public bool Flgmca { get; set; }

    /// <summary>
    /// Indicador de Modulo de Cobranza
    /// </summary>
    public bool Flgcob { get; set; }

    /// <summary>
    /// Indicador de Utilidades
    /// </summary>
    public bool Flguti { get; set; }

    public virtual ICollection<Mstobj> Mstobjs { get; set; } = new List<Mstobj>();

    public virtual ICollection<Mstrol> Mstrols { get; set; } = new List<Mstrol>();
}