// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Objectos Asegurables
/// </summary>
public partial class Mstobj
{
    /// <summary>
    /// Identity del Maestro de Objeto
    /// </summary>
    public int Ideobj { get; set; }

    /// <summary>
    /// Ide de la Compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Codigo de objetos
    /// </summary>
    public string Codobj { get; set; }

    /// <summary>
    /// Descripción del Objeto 
    /// </summary>
    public string Dscobj { get; set; }

    /// <summary>
    /// Tipo del Objeto
    /// </summary>
    public int Tipobj { get; set; }

    /// <summary>
    /// Modulo del Objeto
    /// </summary>
    public int Modobj { get; set; }

    public int? Profun { get; set; }

    /// <summary>
    /// Identity del Objeto Padre
    /// </summary>
    public int? Ideobjpad { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Número de Objeto a Asegurar
    /// </summary>
    public int Numobjsec { get; set; }

    /// <summary>
    /// Código de Objecto de Referencia
    /// </summary>
    public string Codobjref { get; set; }

    public string Icono { get; set; }

    public string Url { get; set; }

    public string Controlador { get; set; }

    public string Accion { get; set; }

    public virtual Mstobj IdeobjpadNavigation { get; set; }

    public virtual ICollection<Mstobj> InverseIdeobjpadNavigation { get; set; } = new List<Mstobj>();

    public virtual Mstorigen ModobjNavigation { get; set; }

    public virtual ICollection<Relrolobj> Relrolobjs { get; set; } = new List<Relrolobj>();
}