// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Plan de Venta 
/// </summary>
public partial class Mstplavtum
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Ideplavta { get; set; }

    /// <summary>
    /// Identity de Compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Codigo del plan de venta.
    /// </summary>
    public string Codplavta { get; set; }

    /// <summary>
    /// Descripcion del plan de Ventas
    /// </summary>
    public string Dscplavta { get; set; }

    /// <summary>
    /// Estado del plan de Venta (0=Activo, 1=Inactivo)
    /// </summary>
    public bool Estplavta { get; set; }

    /// <summary>
    /// Fecha Inicial del Plan de Venta
    /// </summary>
    public DateOnly Fchini { get; set; }

    /// <summary>
    /// Fecha Final del Plan de Venta
    /// </summary>
    public DateOnly Fchfin { get; set; }

    /// <summary>
    /// Cantidad de meses de cortesia del plan de venta
    /// </summary>
    public byte Cntmescor { get; set; }

    /// <summary>
    /// Numero del mes que se pagara anticipado.
    /// </summary>
    public byte Mesant { get; set; }

    /// <summary>
    /// Porcentaje de Descuento del Plan de Venta
    /// </summary>
    public decimal Prcentdes { get; set; }

    /// <summary>
    /// Cantida de meses que se aplicara el descuento
    /// </summary>
    public byte Cntmesdes { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Observacion del Plan de Venta. 
    /// </summary>
    public string Obsplavta { get; set; }

    /// <summary>
    /// Flag que indica si se cobrará el mes anticipado (0 = No cobra mes anticipado, 1= Cobra mes anticipado)
    /// </summary>
    public bool Flgmesant { get; set; }

    /// <summary>
    /// Tipo de Descuento (1 = Porcentaje, 2 = Monto)
    /// </summary>
    public byte Tipdescto { get; set; }

    public int? Idtipopv { get; set; }

    public string Tipo { get; set; }

    public virtual ICollection<Detcnt> Detcnts { get; set; } = new List<Detcnt>();

    public virtual ICollection<Detplavtum> Detplavta { get; set; } = new List<Detplavtum>();
}