// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstprefac
{
    public int Ideprefac { get; set; }

    public int Mesfac { get; set; }

    public int Aniofac { get; set; }

    public int Idecli { get; set; }

    public int Idecnt { get; set; }

    public int Idesuc { get; set; }

    public int Idedep { get; set; }

    public int Idemun { get; set; }

    public int Idezon { get; set; }

    public int Ideszn { get; set; }

    public int Idemon { get; set; }

    public decimal Costoloc { get; set; }

    public decimal Subtotloc { get; set; }

    public decimal Dsctotloc { get; set; }

    public decimal Ivatotloc { get; set; }

    public decimal Mtototloc { get; set; }

    public decimal Costodol { get; set; }

    public decimal Subtotdol { get; set; }

    public decimal Dsctotdol { get; set; }

    public decimal Ivatotdol { get; set; }

    public decimal Mtototdol { get; set; }

    public DateOnly Fchvigencia { get; set; }

    public int Estado { get; set; }

    public decimal TipoCambio { get; set; }

    public int? Idefac { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime FechaCreacion { get; set; }
}