// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Promociones para registro de Servicios en Contratos
/// </summary>
public partial class Mstpromo
{
    public int Idpromo { get; set; }

    public string Descripcion { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime FechaFin { get; set; }

    public int MesesCortesia { get; set; }

    public bool GeneraFactura { get; set; }

    public int Idservicio { get; set; }

    public decimal Monto { get; set; }

    public bool Activa { get; set; }
}