// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Roles de Usuarios
/// </summary>
public partial class Mstrol
{
    /// <summary>
    /// Identity del Maestro de Rol
    /// </summary>
    public int Iderol { get; set; }

    /// <summary>
    /// Identity de la Compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Codigo del Rol
    /// </summary>
    public string Codrol { get; set; }

    /// <summary>
    /// Descripcion del Rol
    /// </summary>
    public string Dscrol { get; set; }

    /// <summary>
    /// Modulo del Rol
    /// </summary>
    public int Modrol { get; set; }

    /// <summary>
    /// Estado del Rol
    /// </summary>
    public short Estrol { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    public virtual Mstorigen ModrolNavigation { get; set; }

    public virtual ICollection<Relrolobj> Relrolobjs { get; set; } = new List<Relrolobj>();

    public virtual ICollection<Relusrrol> Relusrrols { get; set; } = new List<Relusrrol>();
}