// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Sucursales
/// </summary>
public partial class Mstsuc
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idesuc { get; set; }

    /// <summary>
    /// Identity de Compañía
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Codigo de la Sucursal
    /// </summary>
    public string Codsuc { get; set; }

    /// <summary>
    /// Descripcion de la Sucursal
    /// </summary>
    public string Dscsuc { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    public string Codcontr { get; set; }

    public string Codtenenc { get; set; }

    public string Codnodo { get; set; }

    public int? Estintegracion { get; set; }

    public int? Idelibfac { get; set; }

    public int? Idolt { get; set; }

    public int? Idintegracion { get; set; }

    public string Sucursal { get; set; }

    public int? EsFisica { get; set; }

    public string Bodega { get; set; }

    public string PaqueteInventario { get; set; }

    public string CentroCosto { get; set; }

    public bool? Regmovcpe { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public virtual ICollection<Mstcli> Mstclis { get; set; } = new List<Mstcli>();

    public virtual ICollection<Mstlstpre> Mstlstpres { get; set; } = new List<Mstlstpre>();

    public virtual ICollection<Mstubigeo> Mstubigeos { get; set; } = new List<Mstubigeo>();
}