// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstsrvperflow
{
    public int Mstsrvperflowid { get; set; }

    public string Codsrvprd { get; set; }

    public string Idperflow { get; set; }

    public string Nombreperfilflow { get; set; }

    public string Codtenenc { get; set; }
}