// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de clientes suspendidos, en un rango de fecha o cliclo de pago
/// </summary>
public partial class Mstspdido
{
    /// <summary>
    /// Identity del maestro de clientes suspendidos
    /// </summary>
    public int Idespdido { get; set; }

    /// <summary>
    /// Identity de las CIA o compañias
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Identity Interno del Contrato (Identity)
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Identitu Interno de la relación del Servicio y el Contrato
    /// </summary>
    public int Idedetcnt { get; set; }

    /// <summary>
    /// Código del estado del ticket
    /// </summary>
    public string Codesttkt { get; set; }

    /// <summary>
    /// Descipción o nota del motivo de la suspension del cliente
    /// </summary>
    public string Observ { get; set; }

    /// <summary>
    /// Fecha del Registro o ingreso de la suspension del cliente
    /// </summary>
    public DateTime? Fchspdido { get; set; }

    /// <summary>
    /// Fecha activacion del cliente o cambio del estado del cliente a activo
    /// </summary>
    public DateTime? Fchactiva { get; set; }

    /// <summary>
    /// Total o monto de las facturas pendientes a la fecha de la suspension
    /// </summary>
    public decimal? Mtopdente { get; set; }

    /// <summary>
    /// Usuario que ingreso el registro de la suspension.
    /// </summary>
    public string Dscusrreg { get; set; }

    /// <summary>
    /// Usuario o Responsable que autoriza la suspension del cliente.
    /// </summary>
    public string Dscusrauto { get; set; }

    /// <summary>
    /// Identity del estado de la transacción o estado del cliente actual.
    /// </summary>
    public int? Idestatra { get; set; }

    /// <summary>
    /// Total de Linea que posee el cliente en facturas pendientes a la fecha de la suspensión.
    /// </summary>
    public int? Totlin { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Mes de proceso de facturacion del cliente
    /// </summary>
    public int? Mesfac { get; set; }

    /// <summary>
    /// Año de proceso de facturación del cliente o mensualidad.
    /// </summary>
    public int? Yerfac { get; set; }

    /// <summary>
    /// Número de documento de la orden del suspendido o correlativo de las suspensiones.
    /// </summary>
    public string Nodocument { get; set; }

    public int Tap { get; set; }

    /// <summary>
    /// Resultado de la suspension:
    /// 0 - Vigente
    /// 1 - Activacion
    /// 2 - Corte
    /// </summary>
    public int? Proceso { get; set; }

    public virtual Mstcnt IdecntNavigation { get; set; }

    public virtual Detcnt IdedetcntNavigation { get; set; }
}