// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Servicio
/// </summary>
public partial class Mstsrvprd
{
    public int Idesrvprd { get; set; }

    public int Ideclssrvprd { get; set; }

    /// <summary>
    /// Identity de la Compañía
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Código del Item
    /// </summary>
    public string Codsrvprd { get; set; }

    /// <summary>
    /// Descripción del Item
    /// </summary>
    public string Dscsrvprd { get; set; }

    /// <summary>
    /// Tipo de Item. 1=Producto, 2=Servicio, 4=Grupo, 8=Cargo, 16=Descuento
    /// </summary>
    public int Idetipsrvprd { get; set; }

    /// <summary>
    /// Genera Orden Técnica Si o No
    /// </summary>
    public bool Flggenord { get; set; }

    /// <summary>
    /// Porcentaje del impuesto del valor agregado
    /// </summary>
    public decimal Prcent { get; set; }

    /// <summary>
    /// Permitir Modificacion de los valores 
    /// </summary>
    public bool Flgmodval { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// ¿Es un servicio adicional?
    /// </summary>
    public bool Flgsrvadi { get; set; }

    /// <summary>
    /// Identity de la Cuenta Contable de Venta
    /// </summary>
    public int? Idectavta { get; set; }

    /// <summary>
    /// Identity de la Cuenta Contable del IVA
    /// </summary>
    public int? Idectaiva { get; set; }

    /// <summary>
    /// Patron Contable de Ingreso sobre Venta - Segmento 2
    /// </summary>
    public string Patctavta { get; set; }

    /// <summary>
    /// Patron Contable de Cuenta x Cobrar - Segmento 2
    /// </summary>
    public string Patctacxc { get; set; }

    /// <summary>
    /// Patron Contable de Cuenta x Cobrar - Incobrable - Segmento 2
    /// </summary>
    public string Patctacxcinc { get; set; }

    /// <summary>
    /// Patron Contable de Descuento s/ Venta - Segmento 2
    /// </summary>
    public string Patctadscvta { get; set; }

    /// <summary>
    /// Identity de la Cuenta Contable de Venta de Contado
    /// </summary>
    public int? Idectavtacon { get; set; }

    /// <summary>
    /// Patron Contable de Ingreso sobre Venta de Contado - Segmento 2
    /// </summary>
    public string Patctavtacon { get; set; }

    /// <summary>
    /// Flag que indica si entrará en la validación del balance de clientes y balance de Facturación (0=No, 1=Si)
    /// </summary>
    public bool? Flgbalcli { get; set; }

    public decimal? PreBaseLoc { get; set; }

    public decimal? PreBaseFor { get; set; }

    public decimal? Mbps { get; set; }

    public int? Flgcombo { get; set; }

    public string CuentaContable { get; set; }

    public bool? Activo { get; set; }

    public int? Prioridad { get; set; }

    public bool? ProvisionaCpe { get; set; }

    public virtual ICollection<Detcnt> DetcntIdesrvprdNavigations { get; set; } = new List<Detcnt>();

    public virtual ICollection<Detcnt> DetcntMstsrvprds { get; set; } = new List<Detcnt>();

    public virtual ICollection<Detfac> Detfacs { get; set; } = new List<Detfac>();

    public virtual ICollection<Detplavtum> Detplavta { get; set; } = new List<Detplavtum>();

    public virtual ICollection<Detplavtasrv> Detplavtasrvs { get; set; } = new List<Detplavtasrv>();

    public virtual ICollection<Detsrvord> Detsrvords { get; set; } = new List<Detsrvord>();

    public virtual Mstclssrvprd IdeclssrvprdNavigation { get; set; }

    public virtual Msttipsrvprd IdetipsrvprdNavigation { get; set; }

    public virtual ICollection<Mstlstpre> Mstlstpres { get; set; } = new List<Mstlstpre>();
}