// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Ticket (trouble ticket)
/// </summary>
public partial class Mstticket
{
    /// <summary>
    /// Id Interno del Ticket
    /// </summary>
    public int Ideticket { get; set; }

    public int Idecia { get; set; }

    /// <summary>
    /// Fecha de Emisión
    /// </summary>
    public DateTime Fchemi { get; set; }

    public DateTime? Fchprg { get; set; }

    /// <summary>
    /// Id de la Clase de la Orden
    /// </summary>
    public int Ideclsord { get; set; }

    /// <summary>
    /// Id de la Orden que es atendida
    /// </summary>
    public int Ideord { get; set; }

    /// <summary>
    /// Id Interno del Contrato (Identity)
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Id Interno de la relación del Servicio y el Contrato
    /// </summary>
    public int Idedetcnt { get; set; }

    /// <summary>
    /// Código del estado del ticket
    /// </summary>
    public string Codesttkt { get; set; }

    /// <summary>
    /// Id del tipo de Aviso
    /// </summary>
    public int Idetipavi { get; set; }

    /// <summary>
    /// Persona de Contacto
    /// </summary>
    public string Percontac { get; set; }

    /// <summary>
    /// Flag que indica si generará orden 
    /// </summary>
    public bool Flgasigna { get; set; }

    /// <summary>
    /// Id del tecnico de Campo que tiene el ticket Asignada
    /// </summary>
    public int? Idetecasg { get; set; }

    /// <summary>
    /// Observacion de la Orden( A nivel de cabezera se guardará el ultimo comentario)
    /// </summary>
    public string Observ { get; set; }

    /// <summary>
    /// Diagnostico que el tecnico brinda al ticket
    /// </summary>
    public string Diagco { get; set; }

    /// <summary>
    /// Fecha de entrega de la orden al tecnico.
    /// </summary>
    public DateTime? Fchent { get; set; }

    public DateTime? Fchini { get; set; }

    /// <summary>
    /// Fecha de ejecucion de la orden.
    /// </summary>
    public DateTime? Fcheje { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Flag que indica si la orden ya ha sido impresa.
    /// </summary>
    public bool Flgimp { get; set; }

    /// <summary>
    /// Flag o Bandera que indica si la orden va a ser impresa o fue seleccionada
    /// </summary>
    public bool Impord { get; set; }

    public int? Ideaveria { get; set; }

    public bool? Flgequipo { get; set; }

    public int? Idnivel { get; set; }

    public bool? Priorizar { get; set; }

    public int? Idezontec { get; set; }

    public DateTime? Fchfin { get; set; }

    public int? Idservicio { get; set; }

    public int? Idvendedor { get; set; }

    public int? Idcuadrilla { get; set; }

    public int? IdtipoInstalacion { get; set; }

    public DateTime? Fchven { get; set; }

    public virtual Mstcnt IdecntNavigation { get; set; }

    public virtual Detcnt IdedetcntNavigation { get; set; }

    public virtual Msttec IdetecasgNavigation { get; set; }
}