// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Técnico
/// </summary>
public partial class Msttec
{
    /// <summary>
    /// Id Interno
    /// </summary>
    public int Idetec { get; set; }

    public int Idecia { get; set; }

    public string Codtec { get; set; }

    public string Apepritec { get; set; }

    public string Apesegtec { get; set; }

    /// <summary>
    /// Nombre del Tecnico
    /// </summary>
    public string Nomtec { get; set; }

    /// <summary>
    /// Telefono del Tecnico
    /// </summary>
    public string Teltec { get; set; }

    /// <summary>
    /// Celular del Tecnico
    /// </summary>
    public string Celtec { get; set; }

    /// <summary>
    /// Categoria del Tecnico
    /// </summary>
    public int Idecattec { get; set; }

    /// <summary>
    /// Estado del tecnico (1 = Activo, 2 = Inactivo)
    /// </summary>
    public short Esttec { get; set; }

    /// <summary>
    /// Flag que indica si el tecnico es el predeterminado
    /// </summary>
    public bool Flgpretdo { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    public int? Ideusr { get; set; }

    public bool? Flgtablet { get; set; }
}