// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Tipo de Servicio Producto
/// </summary>
public partial class Msttipsrvprd
{
    /// <summary>
    /// Identity del Tipo de Servicio o Producto
    /// </summary>
    public int Idetipsrvprd { get; set; }

    /// <summary>
    /// Identity de la Compañía
    /// </summary>
    public int Idecia { get; set; }

    public string Codtipsrvprd { get; set; }

    public string Dsctipsrvprd { get; set; }

    public byte Numtipsrvprd { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    public virtual ICollection<Mstsrvprd> Mstsrvprds { get; set; } = new List<Mstsrvprd>();
}