// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Tabla maestro de tipos de ubicaciones geograficas o claves de ubicaciones geograficas.
/// </summary>
public partial class Msttipubigeo
{
    /// <summary>
    /// Identity del tipo de ubicacion geografica
    /// </summary>
    public int Idetipubigeo { get; set; }

    /// <summary>
    /// Identity del CIA o de la compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Descripción del tipo de ubicación geografica
    /// </summary>
    public string Dsctipubigeo { get; set; }

    /// <summary>
    /// Codigo o tipo de Ubicación Geografica
    /// </summary>
    public string Tipubigeo { get; set; }

    /// <summary>
    /// Númerador o identificador del tipo de ubicacion geografica
    /// </summary>
    public int? Numtipubigeo { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }
}