// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Ubicación Geografica
/// </summary>
public partial class Mstubigeo
{
    /// <summary>
    /// Id interno
    /// </summary>
    public int Ideubigeo { get; set; }

    /// <summary>
    /// Id de la Compañia
    /// </summary>
    public int Idecia { get; set; }

    public int Idesuc { get; set; }

    /// <summary>
    /// Codigo de la Ubicacion Geografica
    /// </summary>
    public string Codubigeo { get; set; }

    /// <summary>
    /// Tipo de Ubicacion geografica (DP=Departamento, MU=Municipio, ZN=Zona, SZ =Sub-Zona)
    /// </summary>
    public string Tipubigeo { get; set; }

    /// <summary>
    /// Descripcion de la ubicacion geografica
    /// </summary>
    public string Dscubigeo { get; set; }

    /// <summary>
    /// Id del Padre de la ubicacion geografica
    /// </summary>
    public int? Idepaduge { get; set; }

    /// <summary>
    /// Usuario que creo el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// IP de PC Creación
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name de PC de Creación
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP de PC de Modificación
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name de PC de Modificación
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Identity de Cuenta por Cobrar
    /// </summary>
    public int? Idectacxc { get; set; }

    /// <summary>
    /// Identity de Cuenta Contable de Cuentas por Cobrar Incobrable
    /// </summary>
    public int? Idectacxcinc { get; set; }

    /// <summary>
    /// Patron Contable de Cuenta x Cobrar - Segmento 1
    /// </summary>
    public string Patctacxc { get; set; }

    /// <summary>
    /// Patron Contable de Cuenta x Cobrar - Incobrable - Segmento 1
    /// </summary>
    public string Patctacxcinc { get; set; }

    /// <summary>
    /// Patron Contable de Ingresos por Ventas - Segmento 1
    /// </summary>
    public string Patctavta { get; set; }

    /// <summary>
    /// Id Cuenta Contable de Ingresos por Ventas de Contado
    /// </summary>
    public int? Idectavtacon { get; set; }

    /// <summary>
    /// Patron Contable de Ingresos por Ventas de Contado - Segmento 1
    /// </summary>
    public string Patctavtacon { get; set; }

    /// <summary>
    /// Id del Agente del tipo Colector
    /// </summary>
    public int? Ideagecol { get; set; }

    /// <summary>
    /// Id del Agente del tipo Colector
    /// </summary>
    public int? Ideageven { get; set; }

    /// <summary>
    /// Id del Técnico
    /// </summary>
    public int? Idetec { get; set; }

    public int? CasasPasadas { get; set; }

    public string Codtecnico { get; set; }

    public DateOnly? FechaApertura { get; set; }

    public decimal PorcpenBajo { get; set; }

    public decimal PorcpenMedio { get; set; }

    public decimal PorcpenAlto { get; set; }

    public int? Idpoligono { get; set; }

    public int? Idetecanterior { get; set; }

    public bool? Activo { get; set; }

    public virtual Mstubigeo IdepadugeNavigation { get; set; }

    public virtual Mstsuc IdesucNavigation { get; set; }

    public virtual ICollection<Mstubigeo> InverseIdepadugeNavigation { get; set; } = new List<Mstubigeo>();

    public virtual ICollection<Mstcli> MstcliIdedepNavigations { get; set; } = new List<Mstcli>();

    public virtual ICollection<Mstcli> MstcliIdemunNavigations { get; set; } = new List<Mstcli>();

    public virtual ICollection<Mstcli> MstcliIdesznNavigations { get; set; } = new List<Mstcli>();

    public virtual ICollection<Mstcli> MstcliIdezonNavigations { get; set; } = new List<Mstcli>();

    public virtual ICollection<Mstlstpre> MstlstpreIdedepNavigations { get; set; } = new List<Mstlstpre>();

    public virtual ICollection<Mstlstpre> MstlstpreIdemunNavigations { get; set; } = new List<Mstlstpre>();

    public virtual ICollection<Mstlstpre> MstlstpreIdesznNavigations { get; set; } = new List<Mstlstpre>();

    public virtual ICollection<Mstlstpre> MstlstpreIdezonNavigations { get; set; } = new List<Mstlstpre>();

    public virtual ICollection<Relageubi> RelageubiIdedepNavigations { get; set; } = new List<Relageubi>();

    public virtual ICollection<Relageubi> RelageubiIdemunNavigations { get; set; } = new List<Relageubi>();

    public virtual ICollection<Relageubi> RelageubiIdesznNavigations { get; set; } = new List<Relageubi>();

    public virtual ICollection<Relageubi> RelageubiIdezonNavigations { get; set; } = new List<Relageubi>();
}