// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Maestro de Usuarios
/// </summary>
public partial class Mstusr
{
    /// <summary>
    /// Identity del Maestro de Roles 
    /// </summary>
    public int Ideusr { get; set; }

    /// <summary>
    /// Identity de la Compañia
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Codigo del Usuario
    /// </summary>
    public string Codusr { get; set; }

    /// <summary>
    /// Nombre de Usuario
    /// </summary>
    public string Nomusr { get; set; }

    /// <summary>
    /// Primer Apellido 
    /// </summary>
    public string Apepri { get; set; }

    /// <summary>
    /// Segundo Apellido
    /// </summary>
    public string Apreseg { get; set; }

    /// <summary>
    /// Estado del Usuario
    /// </summary>
    public short Estusr { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Password del usuario
    /// </summary>
    public string Usrpas { get; set; }

    public int? Rolpaq { get; set; }

    public string Login { get; set; }

    public int Sql { get; set; }

    public string Empleado { get; set; }

    public virtual ICollection<Relusrrol> Relusrrols { get; set; } = new List<Relusrrol>();
}