// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstvalfac
{
    /// <summary>
    /// Identity de la tabla MSTVALFAC
    /// </summary>
    public int Idevalfac { get; set; }

    /// <summary>
    /// Indentity del Cliente
    /// </summary>
    public int Idecli { get; set; }

    /// <summary>
    /// Identity del Contrato del Cliente
    /// </summary>
    public int Idecnt { get; set; }

    /// <summary>
    /// Identity del Servicio del Cliente
    /// </summary>
    public int Idedetcnt { get; set; }

    public int Ideapefac { get; set; }

    /// <summary>
    /// Identity de las CIAS o Compañias
    /// </summary>
    public int Idecia { get; set; }

    public DateTime Crefch { get; set; }

    public DateTime Modfch { get; set; }

    public string Creusr { get; set; }

    public string Modusr { get; set; }

    public string Creips { get; set; }

    public string Crehsn { get; set; }

    public string Modips { get; set; }

    public string Modhsn { get; set; }

    /// <summary>
    /// Flag que indica el estado de la validacion(0=Sin Utilizar 1=Utilizada)
    /// </summary>
    public bool Flgest { get; set; }

    public virtual Mstapefac IdeapefacNavigation { get; set; }

    public virtual Mstcli IdecliNavigation { get; set; }

    public virtual Mstcnt IdecntNavigation { get; set; }

    public virtual Detcnt IdedetcntNavigation { get; set; }
}