// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Mstventgeo
{
    public int Idventa { get; set; }

    public int Ideftocnt { get; set; }

    public int Iduser { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public string Creusr { get; set; }

    public DateTime Crefch { get; set; }
}