// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Parámetro de Facturación
/// </summary>
public partial class Parfactur
{
    /// <summary>
    /// Identity de Parámetro de Facturación
    /// </summary>
    public int Ideparfac { get; set; }

    /// <summary>
    /// Identity de la Compañía
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Cantidad de Dias de Plazo de la Factura
    /// </summary>
    public int Cntdiaplafac { get; set; }

    /// <summary>
    /// Identity de la Moneda en que se facturará y se cobrará
    /// </summary>
    public int Idemonfac { get; set; }

    public string Leyfac { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    /// <summary>
    /// Configuración Contable del Cuenta x Cobrar (1= Cta Contable, 2 = Patrón de Cuenta)
    /// </summary>
    public byte Cnfctacxc { get; set; }

    /// <summary>
    /// Configuración Contable del Cuenta x Cobrar - Incobrable(1= Cta Contable, 2 = Patrón de Cuenta)
    /// </summary>
    public byte Cnfctacxcinc { get; set; }

    /// <summary>
    /// Configuración Contable del Ingreso x Venta (1= Cta Contable, 2 = Patrón de Cuenta)
    /// </summary>
    public byte Cnfctavta { get; set; }

    /// <summary>
    /// Configuración Contable del Ingreso x Venta de Contado (1= Cta Contable, 2 = Patrón de Cuenta)
    /// </summary>
    public byte Cnfctavtacon { get; set; }

    /// <summary>
    /// Monto o Valor de la NC - Descuento
    /// </summary>
    public decimal? Mtoncloc { get; set; }
}