// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Relageubi
{
    /// <summary>
    /// Identity de la tabla 
    /// </summary>
    public int Ideageubi { get; set; }

    public int Idecia { get; set; }

    /// <summary>
    /// Identity del Agente
    /// </summary>
    public int Ideagente { get; set; }

    /// <summary>
    /// Identity del Departamento
    /// </summary>
    public int Idedep { get; set; }

    /// <summary>
    /// Identity del Municipio
    /// </summary>
    public int Idemun { get; set; }

    /// <summary>
    /// Identity de la Zona
    /// </summary>
    public int Idezon { get; set; }

    /// <summary>
    /// Identity de la Sub Zona
    /// </summary>
    public int? Ideszn { get; set; }

    public string Creusr { get; set; }

    public DateTime Crefch { get; set; }

    public string Modusr { get; set; }

    public DateTime Modfch { get; set; }

    public string Creips { get; set; }

    public string Crehsn { get; set; }

    public string Modips { get; set; }

    public string Modhsn { get; set; }

    /// <summary>
    /// Tipo de Relacion (2=Relacionar Colectores,1= Relacionar Vendedores)
    /// </summary>
    public byte Idetiprel { get; set; }

    public virtual Mstubigeo IdedepNavigation { get; set; }

    public virtual Mstubigeo IdemunNavigation { get; set; }

    public virtual Mstubigeo IdesznNavigation { get; set; }

    public virtual Mstubigeo IdezonNavigation { get; set; }
}