// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

/// <summary>
/// Relación Roles y Objetos Asegurables
/// </summary>
public partial class Relrolobj
{
    /// <summary>
    /// Identity de la Relacion Rol - Objeto
    /// </summary>
    public int Iderolobj { get; set; }

    /// <summary>
    /// Identity del Maestro de Roles
    /// </summary>
    public int Iderol { get; set; }

    /// <summary>
    /// Identity del Maestro de Objeto
    /// </summary>
    public int Ideobj { get; set; }

    /// <summary>
    /// Identity e indeficador unico de la CIA
    /// </summary>
    public int Idecia { get; set; }

    /// <summary>
    /// Permiso de Ejecucion
    /// </summary>
    public bool Flgexe { get; set; }

    /// <summary>
    /// Fecha de Creación
    /// </summary>
    public DateTime Crefch { get; set; }

    /// <summary>
    /// Fecha de Modificación
    /// </summary>
    public DateTime Modfch { get; set; }

    /// <summary>
    /// Usuario que creó el registro
    /// </summary>
    public string Creusr { get; set; }

    /// <summary>
    /// Usuario que modificó el registro
    /// </summary>
    public string Modusr { get; set; }

    /// <summary>
    /// IP desde donde se creo el registro
    /// </summary>
    public string Creips { get; set; }

    /// <summary>
    /// Host Name desde donde se creo el registro
    /// </summary>
    public string Crehsn { get; set; }

    /// <summary>
    /// IP desde donde se modifico el registro
    /// </summary>
    public string Modips { get; set; }

    /// <summary>
    /// Host Name desde donde se modifico el registro
    /// </summary>
    public string Modhsn { get; set; }

    public virtual Mstobj IdeobjNavigation { get; set; }

    public virtual Mstrol IderolNavigation { get; set; }
}