// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class Relusrsuc
{
    public int Idrelusrsuc { get; set; }

    public int? Idusuario { get; set; }

    public string Codusr { get; set; }

    public int? Idesuc { get; set; }
}