// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class ResultadoAnulacionMora
{
    public int? Idcontrato { get; set; }

    public int? NoContrato { get; set; }

    public int? IddetalleContrato { get; set; }

    public int? Idfactura { get; set; }

    public int? Idestado { get; set; }

    public int? Aplicado { get; set; }

    public string Mensaje { get; set; }

    public DateTime? Fecha { get; set; }
}