// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModeloPrincipal.Entity
{
    public partial class spObtenerFacturasColectorResult
    {
        [StringLength(17)]
        public string IDUnico { get; set; }
        public int IDContrato { get; set; }
        public int NoContrato { get; set; }
        [StringLength(50)]
        public string EMAIL1 { get; set; }
        [StringLength(50)]
        public string EMAIL2 { get; set; }
        public byte? DiaPago { get; set; }
        public int? IDColector { get; set; }
        [StringLength(76)]
        public string Colector { get; set; }
        [StringLength(76)]
        public string EntregadoPor { get; set; }
        [StringLength(15)]
        public string NumeroFaja { get; set; }
        public int IDSucursal { get; set; }
        [StringLength(50)]
        public string Sucursal { get; set; }
        [StringLength(17)]
        public string Factura { get; set; }
        [Column("SALDO", TypeName = "decimal(18,2)")]
        public decimal SALDO { get; set; }
        public string EstadoPagoFactura { get; set; }
        public int IDEUBIGEO { get; set; }
        [StringLength(50)]
        public string Zona { get; set; }
        public DateOnly? FECHA { get; set; }
        public int PrimeraMensualidad { get; set; }
        [StringLength(100)]
        public string NOMFAC { get; set; }
        [StringLength(50)]
        public string ESTADO_CONTRATO { get; set; }
        public bool SuspensionCompleta { get; set; }
    }
}
