// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ModeloPrincipal.Entity
{
    public partial class spObtenerContratosDisponiblesResult
    {
        public int IDEFTOCNT { get; set; }
        public int IDEAGENTE { get; set; }
        [StringLength(255)]
        public string AGENTE { get; set; }
        public int IDESUC { get; set; }
        [StringLength(255)]
        public string SUCURSAL { get; set; }
        public byte IDEESTFTO { get; set; }
    }
}
