// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class SuscripcionesFacturaDigital
{
    public int IdContrato { get; set; }

    public int NumeroContrato { get; set; }

    public int NumeroFactura { get; set; }

    public string Ciclo { get; set; }

    public string Cliente { get; set; }

    public string Correo { get; set; }

    public string Serie { get; set; }

    public bool Procesada { get; set; }

    public DateTime? FechaProceso { get; set; }

    public int? Sucursal { get; set; }
}