// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class TblCatalogoComisionVtum
{
    public int Idservicio { get; set; }

    public decimal? MontoComisionVta { get; set; }

    public decimal? MontoComisionRec { get; set; }
}