// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class TrackingTecnico
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Tecnico { get; set; }

    public int Idsuc { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public DateTime Timestamp { get; set; }
}