// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwContratosW
{
    public int Idcontrato { get; set; }

    public string Sucursal { get; set; }

    public int NumeroContrato { get; set; }

    public int Idcliente { get; set; }

    public string FacturarA { get; set; }

    public string DireccionContrato { get; set; }

    public DateOnly FechaInicio { get; set; }

    public byte? Diapag { get; set; }

    public string Solvencia { get; set; }

    public string EstadoContrato { get; set; }

    public string Departamento { get; set; }

    public string Municipio { get; set; }

    public string Zona { get; set; }

    public string Subzona { get; set; }

    public string Email1 { get; set; }

    public string Email2 { get; set; }

    public string Celcli { get; set; }
}