// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwcontratoCliente
{
    public int Contrato { get; set; }

    public string Mail { get; set; }

    public string Name { get; set; }

    public string Direccion { get; set; }

    public int? Idempresa { get; set; }
}