// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwContratoActivar
{
    public int Ideftocnt { get; set; }

    public int Idcontrato { get; set; }

    public int? Idtecnologia { get; set; }

    public string Tenencia { get; set; }

    public string Servicio { get; set; }

    public int Contrato { get; set; }

    public int? EstadoContratoNum { get; set; }

    public string EstadoContrato { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Dicmacmm { get; set; }

    public string Sucursal { get; set; }

    public string CodSuc { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public int IdServicio { get; set; }

    public bool? Primario { get; set; }

    public string Realm { get; set; }

    public int IdSucursal { get; set; }

    public int? Idperfil { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public string Faja { get; set; }

    public bool? SuspensionCompleta { get; set; }
}