// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwContratosServiciosW
{
    public int Idcontrato { get; set; }

    public int IddetalleContrato { get; set; }

    public int Idservicio { get; set; }

    public string Estadoservicio { get; set; }

    public decimal PrecioLocal { get; set; }

    public decimal PrecioDolar { get; set; }

    public int? Nuniss { get; set; }

    public string Dicmaccm { get; set; }
}