// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwFacturasW
{
    public int Idcontrato { get; set; }

    public DateOnly FechaVencimiento { get; set; }

    public DateOnly FechaCancelacion { get; set; }

    public int Idfactura { get; set; }

    public string Serie { get; set; }

    public int NumeroFactura { get; set; }

    public string Factura { get; set; }

    public string Periodo { get; set; }

    public decimal SubtotalLocal { get; set; }

    public decimal IvaLocal { get; set; }

    public decimal TotalLocal { get; set; }

    public decimal SaldoLocal { get; set; }

    public decimal SubtotalDolar { get; set; }

    public decimal IvaDolar { get; set; }

    public decimal TotalDolar { get; set; }

    public decimal SaldoDolar { get; set; }

    public string CodPago { get; set; }

    public string DescripcionPago { get; set; }

    public byte CodEstado { get; set; }

    public string DescripcionEstado { get; set; }

    public bool TipoFactura { get; set; }

    public string DescripcionTipo { get; set; }

    public string Colector { get; set; }

    public byte MesFactura { get; set; }

    public int AnioFactura { get; set; }
}