// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwFacturasServiciosW
{
    public int Idfactura { get; set; }

    public int IddetaleFactura { get; set; }

    public int? IdedetalleContrato { get; set; }

    public int Idservicio { get; set; }

    public decimal SubtotalLocal { get; set; }

    public decimal IvaLocal { get; set; }

    public decimal DescuentoLocal { get; set; }

    public decimal TotalLocal { get; set; }

    public decimal SubtotalDolar { get; set; }

    public decimal IvaDolar { get; set; }

    public decimal DescuentoDolar { get; set; }

    public decimal TotalDolar { get; set; }

    public decimal? TipoCambio { get; set; }
}