// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwHistorialFactura
{
    public int Id { get; set; }

    public int NumeroContrato { get; set; }

    public int IdFactura { get; set; }

    public string NumeroFactura { get; set; }

    public DateOnly FechaFactura { get; set; }

    public decimal SubTotal { get; set; }

    public decimal Iva { get; set; }

    public decimal Total { get; set; }

    public string Cliente { get; set; }

    public DateOnly? FechaP { get; set; }

    public string Direccion { get; set; }

    public string Correo1 { get; set; }

    public string Correo2 { get; set; }

    public string Codsts { get; set; }

    public byte Stdfac { get; set; }

    public string Nomfac { get; set; }

    public string Servicios { get; set; }
}