// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwMovimientosEquiposListado
{
    public int? NumMovimiento { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? Idmovimiento { get; set; }

    public string BodegaOrigen { get; set; }

    public string BodegaDestino { get; set; }

    public string Mac { get; set; }

    public string NumeroSeriePon { get; set; }

    public string Observaciones { get; set; }

    public string UsuarioRegistro { get; set; }
}