// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwObtenerEquipoContrato
{
    public int Contrato { get; set; }

    public string IdentificadorEquipo { get; set; }
}