// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwPlanificacione
{
    public int IdatencionTicket { get; set; }

    public DateOnly Fecha { get; set; }

    public int Idcuadrilla { get; set; }

    public string Cuadrilla { get; set; }

    public int Idtecnico { get; set; }

    public string Tecnico { get; set; }

    public int Ot { get; set; }

    public DateOnly? Emitida { get; set; }

    public string Clase { get; set; }

    public string Tipo { get; set; }

    public string EstadoOt { get; set; }

    public bool Prioridad { get; set; }

    public int Idestado { get; set; }

    public string EstadoAtencion { get; set; }

    public int? Idresultado { get; set; }

    public string ResultadoAtencion { get; set; }

    public int Idsucursal { get; set; }

    public DateTime? FechaHoraInicio { get; set; }

    public DateTime? FechaHoraFin { get; set; }
}