// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloPrincipal.Entity;

public partial class VwServiciosW
{
    public int Idservicio { get; set; }

    public int IdClase { get; set; }

    public string ClaseServicio { get; set; }

    public string Servicio { get; set; }

    public decimal? PrecioBaseLocal { get; set; }

    public decimal? PrecioBaseDolar { get; set; }

    public int? Mbps { get; set; }

    public int Internet { get; set; }
}